-- MySQL Script generated by MySQL Workbench
-- Thu Apr 11 09:40:11 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema gestao_pessoas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gestao_pessoas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gestao_pessoas` DEFAULT CHARACTER SET utf8 ;
USE `gestao_pessoas` ;

-- -----------------------------------------------------
-- Table `gestao_pessoas`.`pessoas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestao_pessoas`.`pessoas` (
  `id_pessoa` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_pessoa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestao_pessoas`.`enderecos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestao_pessoas`.`enderecos` (
  `id_endereco` INT NOT NULL AUTO_INCREMENT,
  `cidade` VARCHAR(45) NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `pessoas_id_pessoa` INT NOT NULL,
  PRIMARY KEY (`id_endereco`, `pessoas_id_pessoa`),
  INDEX `fk_enderecos_pessoas_idx` (`pessoas_id_pessoa` ASC) VISIBLE,
  CONSTRAINT `fk_enderecos_pessoas`
    FOREIGN KEY (`pessoas_id_pessoa`)
    REFERENCES `gestao_pessoas`.`pessoas` (`id_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
